### ISSUE TITLE
[ENHANCEMENT] Improve process to permit multiple document compilation passes

### ISSUE THREAD

**Issue by remifrazierucsf** [susom/multi-signature-consent#2]
## Is your feature request related to a problem? Please describe.
The module currently is single-tracked: It permits only the creation of a single compiled PDF using a set of input forms.  This limits its use in a REDCap project to a single compiled form. 

## Describe the solution you'd like
Update the module to add a loop structure around its configuration, allowing users to define multiple sequences of forms to convert to PDFs.

## Additional context
Research projects often have multiple signature-controlled events (eg, an initial consent, as well as a human research subjects form, followed by possible re-consents or consent modifications as a study progresses).

**Comment by 123andy** [comment]
Please make a pull request and I'm happy to include.  This was an EM for a specific project with limited funding, so it goes...

**Comment by remifrazierucsf** [comment]
Yep - I'm hard at work on the PR for this.  It should go in tomorrow (I hope).
________________________________
